### ISSUE TITLE
'make' is not recognized

### ISSUE THREAD

**Issue by safo-bora** [ruddra/docker-django#16]
I have error:

_D:\docker-django>make shell-web
'make' is not recognized as an internal or external command,
operable program or batch file._

Should it be run from root folder?

**Comment by ruddra** [comment]
Well, you need to install [Cygwin](https://stackoverflow.com/questions/2532234/how-to-run-a-makefile-in-windows) or [Gnuwin32](https://sourceforge.net/projects/gnuwin32/) in windows to run `make` command. You can look into this stackoverflow answer for more details: https://stackoverflow.com/questions/2532234/how-to-run-a-makefile-in-windows

**Comment by ruddra** [comment]
closing the issue as there is no response from @safo-bora
