### ISSUE TITLE
Python Pandas

### ISSUE THREAD

**Issue by stepanjan** [ruddra/docker-django#22]
Hi, thank you for this Dockerimage. 
I have problems with Pandas and Numpy

its my requirements.pip
amqp==2.4.2
billiard==3.6.0.0
celery==4.3.0
Django==2.2.1
gunicorn==19.9.0
kombu==4.5.0
pytz==2019.1
redis==3.2.1
sqlparse==0.3.0
vine==1.3.0
pandas==0.25.1 

ERROR:
`  .... in build_sources
      File "/tmp/easy_install-lcv5khez/numpy-1.17.3/numpy/distutils/command/build_src.py", line 286, in build_library_sources
      File "/tmp/easy_install-lcv5khez/numpy-1.17.3/numpy/distutils/command/build_src.py", line 369, in generate_sources
      File "numpy/core/setup.py", line 669, in get_mathlib_info
        "depends": tseries_depends,
    RuntimeError: Broken toolchain: cannot link a simple C program
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install -r requirements.pip' returned a non-zero code: 1
`
in next step i try it with apt packages:
Dockerfile
`FROM python:3.8.0-alpine3.10
ENV PYTHONUNBUFFERED 1
ENV C_FORCE_ROOT true
RUN mkdir /src
RUN mkdir /static
WORKDIR /src

# install psycopg2
RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add postgresql-dev \
    && pip install psycopg2 \
    && pip install numpy \ . ###NEW LINE
    && pip install pandas \ ### NEW LINE
    && apk del build-deps

ADD ./src /src
RUN pip install --upgrade pip
RUN pip install -r requirements.pip
CMD python manage.py collectstatic --no-input;python manage.py migrate; gunicorn mydjango.wsgi -b 0.0.0.0:8000 & celery worker --app=myapp.tasks
`

ERROR:
`
  File "/tmp/pip-install-74d91rss/pandas/setup.py", line 409, in build_extensions
        self.check_cython_extensions(self.extensions)
      File "/tmp/pip-install-74d91rss/pandas/setup.py", line 399, in check_cython_extensions
        raise Exception(
    Exception: Cython-generated file 'pandas/_libs/algos.c' not found.
                    Cython is required to compile pandas from a development branch.
                    Please install Cython or download a release package of pandas.
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-74d91rss/pandas/setup.py'"'"'; __file__='"'"'/tmp/pip-install-74d91rss/pandas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1mjw0bgj/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
`
i hope, you can help me

**Comment by ruddra** [comment]
Although i initially thought to put every dependencies for Pandas in dockerfile, but I changed mind and only put the necessary dependencies for django. But I have added instructions on how to use pandas in the [Dockerfile](https://github.com/ruddra/docker-django/blob/master/compose/django/Dockerfile). Also I have created a gist https://gist.github.com/ruddra/870d7a51238ddfa4b50375086c12a4f5 which will work with Pandas. Please let me know if you face any issues. If not, then please close this issue. :)
