### ISSUE TITLE
Using 'networking' between contaniner services insted of just 'linking' then

### ISSUE THREAD

**Issue by baptvit** [ruddra/docker-django#25]
**Describe the solution you'd like**
In future deployment situations 'links' inst a good practice among container services.

**Describe alternatives you've considered**
[Oficial docs](https://docs.docker.com/network/)
[Good example](https://stackoverflow.com/questions/57336734/creating-network-between-two-docker-containers)

**Additional context**
Just a good practice tip for improve yout repo

**Comment by ruddra** [comment]
Thanks for the suggestion, I will look into it.

**Comment by ruddra** [comment]
@helpthx I have added the codes. maybe you can have a look and close the issue :)
