### ISSUE TITLE
fix db name schema

### ISSUE THREAD

**Issue by rodolfosouza** [ruddra/docker-django#27]
please change the variable name in docker-django\.envs\.django
from DATABASE=django_db to DB_NAME=django_db

The Django is creating in schema postgress, not in django_db

another hint... to enable external access to the container db just include these 2 variables
PGHOST=localhost 
PGPORT=5444

**Comment by zachary** [comment]
and change POSTGRES_DATABASE to POSTGRES_DB

**Comment by ruddra** [comment]
I think zachary fixed with PR https://github.com/ruddra/docker-django/pull/28 and https://github.com/ruddra/docker-django/pull/29
