### ISSUE TITLE
Trying localhost on browser not working

### ISSUE THREAD

**Issue by EmilioK0** [ruddra/docker-django#3]
With a clean pull of this repo, when I start the containers and I try to access to the django app via browser it doesn't work. 
If I try localhost:80 it results in a ERR_CONNECTION_REFUSED, no server in this adress
If I try localhost:8000 it results in a ERR_EMPTY_RESPONSE.
Any idea how to solve it?

PS: I'm using Docker on Mac
The lastest log in the web container is:
```
dsz01     | [2017-06-13 12:04:51 +0000] [9] [INFO] Starting gunicorn 19.6.0
dsz01     | [2017-06-13 12:04:51 +0000] [9] [INFO] Listening at: http://127.0.0.1:8000 (9)
dsz01     | [2017-06-13 12:04:51 +0000] [9] [INFO] Using worker: sync
dsz01     | [2017-06-13 12:04:51 +0000] [12] [INFO] Booting worker with pid: 12
```

**Comment by Arlington1985** [comment]
I have same problem, how did you solve it?

**Comment by changchichung** [comment]
me too , I think it`s not working ...

**Comment by ruddra** [comment]
You needed to change some configurations in settings.py to make it working. But in new update, I have discarded everything. Now it should work fine and you should see a working page at `localhost:8000`. 
Please make a fresh pull again and start from `make build` then `make up`
