### ISSUE TITLE
Assistance with the configuring the DB to access psql command

### ISSUE THREAD

**Issue by shaenr** [ruddra/docker-django#32]
if I try to use `make shell-db` and then do `psql` it will tell me that `psql: FATAL:  role "root" does not exist`

How can I configure it so that I can access psql in some way. This is has been my biggest issue with dockerizing django+postgrest and this info might be useful to others as well if you could help me with it.

**Comment by ruddra** [comment]
If you use `psql -U user django_db` to access the database. If you want to use custom user, please update the `.envs>.postgres` file.

**Comment by shaenr** [comment]
> If you use `psql -U user django_db` to access the database. If you want to use custom user, please update the `.envs>.postgres` file.

Thank you for this. I believe I did figure it out eventually. :)
