### ISSUE TITLE
Celery, no module named 'utility'

### ISSUE THREAD

**Issue by horainuri** [ruddra/docker-django#4]
At ligne 41 of the docker-compose.yml there is this line : 

`command: celery worker --app=utility.tasks`

I get this error when I'm trying to run docker-compose up : 

`ModuleNotFoundError: No module named 'utility' `

Is there any way to resolve it ?

**Comment by Brightside56** [comment]
most probably you've changed code of application and renamed it from "utility" to "insert your name here"

**Comment by rganeyev** [comment]
I got the same error, without any change of code.

**Comment by Arlington1985** [comment]
Me too

**Comment by ruddra** [comment]
Try running `celery worker --app=myapp.tasks` if you are using the project which was given with this boilerplate(inside src directory).
