### ISSUE TITLE
Add celery 4.2.0

### ISSUE THREAD

**Issue by gusgene** [ruddra/docker-django#8]
With celery 4.0.0, i had non stable work... 

/usr/local/lib/python3.5/site-packages/celery/platforms.py:792: RuntimeWarning: You're running the worker with superuser privileges: this is
dz01     | absolutely not recommended!
dz01     |
dz01     | Please specify a different user using the -u option.
dz01     |
dz01     | User information: uid=0 euid=0 gid=0 egid=0
dz01     |
dz01     |   uid=uid, euid=euid, gid=gid, egid=egid,
dz01     | Traceback (most recent call last):
dz01     |   File "/usr/local/lib/python3.5/site-packages/kombu/transport/base.py", line 123, in __getattr__
dz01     |     return self[key]
dz01     | KeyError: 'async'
dz01     |
dz01     | During handling of the above exception, another exception occurred:
dz01     |
dz01     | Traceback (most recent call last):
dz01     |   File "/usr/local/bin/celery", line 11, in <module>
dz01     |     sys.exit(main())
dz01     |   File "/usr/local/lib/python3.5/site-packages/celery/__main__.py", line 14, in main
dz01     |     _main()
dz01     |   File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 326, in main
dz01     |     cmd.execute_from_commandline(argv)
dz01     |   File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
dz01     |     super(CeleryCommand, self).execute_from_commandline(argv)))
dz01     |   File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 278, in execute_from_commandline
dz01     |     return self.handle_argv(self.prog_name, argv[1:])
dz01     |   File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 480, in handle_argv
dz01     |     return self.execute(command, argv)
dz01     |   File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 412, in execute
dz01     |     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
dz01     |   File "/usr/local/lib/python3.5/site-packages/celery/bin/worker.py", line 221, in run_from_argv
dz01     |     return self(*args, **options)
dz01     |   File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 241, in __call__
dz01     |     ret = self.run(*args, **kwargs)
dz01     |   File "/usr/local/lib/python3.5/site-packages/celery/bin/worker.py", line 255, in run
dz01     |     **kwargs)
dz01     |   File "/usr/local/lib/python3.5/site-packages/celery/worker/worker.py", line 99, in __init__
dz01     |     self.setup_instance(**self.prepare_args(**kwargs))
dz01     |   File "/usr/local/lib/python3.5/site-packages/celery/worker/worker.py", line 122, in setup_instance
dz01     |     self.should_use_eventloop() if use_eventloop is None
dz01     |   File "/usr/local/lib/python3.5/site-packages/celery/worker/worker.py", line 241, in should_use_eventloop
dz01     |     self._conninfo.transport.implements.async and
dz01     |   File "/usr/local/lib/python3.5/site-packages/kombu/transport/base.py", line 125, in __getattr__
dz01     |     raise AttributeError(key)
dz01     | AttributeError: async
dz01 exited with code 1

**Comment by ruddra** [comment]
done
